// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/forgot-password": {
            "post": {
                "description": "Accepts an email and stores a one-time reset token when the account is eligible. The response is always generic.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Start password reset",
                "parameters": [
                    {
                        "description": "Email address",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/authdto.ForgotPasswordDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/authdto.ForgotPasswordResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/github/callback": {
            "get": {
                "description": "Completes GitHub login, creates a browser session, and redirects back to the OAuth continue URL.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "GitHub auth callback",
                "responses": {
                    "302": {
                        "description": "Redirect to continue URL",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/github/login": {
            "get": {
                "description": "Redirects the browser to GitHub OAuth using the provided OAuth continue URL.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Start GitHub login",
                "parameters": [
                    {
                        "type": "string",
                        "description": "OAuth continue URL",
                        "name": "continue",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Redirect to GitHub",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/login": {
            "post": {
                "description": "Authenticates a local user, creates a browser session, and returns the authenticated user payload.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login with email and password",
                "parameters": [
                    {
                        "description": "Credentials and OAuth continue URL",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/authdto.LoginDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/authdto.SessionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/logout": {
            "post": {
                "description": "Revokes the current browser session and clears auth cookies.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Logout current session",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/authdto.LogoutResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/register": {
            "post": {
                "description": "Creates a local user, auto-signs them in, and returns the authenticated user payload.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a local account",
                "parameters": [
                    {
                        "description": "Registration payload and OAuth continue URL",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/authdto.RegisterDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/authdto.SessionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/reset-password": {
            "post": {
                "description": "Resets the password for a valid token and revokes all active sessions and tokens for that user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Reset local account password",
                "parameters": [
                    {
                        "description": "Reset token and new password",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/authdto.ResetPasswordDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/authdto.ResetPasswordResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/reset-password/validate": {
            "get": {
                "description": "Returns whether a password reset token is valid, expired, invalid, or already used.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Validate password reset token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Reset token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/authdto.ResetPasswordValidationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/session": {
            "get": {
                "description": "Returns the currently authenticated user for the active browser session, or authenticated=false when there is no active session.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Current browser auth session",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/authdto.SessionResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    }
                }
            }
        },
        "/api/v1/gamification/me": {
            "get": {
                "description": "Returns cumulative stats and unlocked achievements for the current authenticated user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gamification"
                ],
                "summary": "Current user gamification",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gamificationdto.MeResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    }
                }
            }
        },
        "/api/v1/health/healthz": {
            "get": {
                "description": "Reports service liveness status.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Liveness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/health.LivenessStatus"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    }
                }
            }
        },
        "/api/v1/health/readyz": {
            "get": {
                "description": "Checks database and Redis connectivity.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Readiness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/health.ReadinessStatus"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    }
                }
            }
        },
        "/api/v1/history/me/sessions": {
            "get": {
                "description": "Returns paginated room history for the current authenticated user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "history"
                ],
                "summary": "Current user sessions",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "ALL",
                            "ACTIVE",
                            "FINISHED",
                            "EXPIRED"
                        ],
                        "type": "string",
                        "description": "Status filter",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "ALL",
                            "ADMIN",
                            "PARTICIPANT"
                        ],
                        "type": "string",
                        "description": "Role filter",
                        "name": "role",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/historydto.SessionListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    }
                }
            }
        },
        "/api/v1/history/rooms/{id}/summary": {
            "get": {
                "description": "Returns aggregated room history, participants, tasks, rounds, and revealed votes.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "history"
                ],
                "summary": "Room summary",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/historydto.RoomSummaryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    }
                }
            }
        },
        "/api/v1/history/teams/{id}/sessions": {
            "get": {
                "description": "Returns paginated room history for a team. Team owner access is required.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "history"
                ],
                "summary": "Team sessions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "ALL",
                            "ACTIVE",
                            "FINISHED",
                            "EXPIRED"
                        ],
                        "type": "string",
                        "description": "Status filter",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/historydto.SessionListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    }
                }
            }
        },
        "/api/v1/oauth2/authorize": {
            "get": {
                "description": "Validates the authorization request and either issues an auth code for an authenticated browser session or redirects the user to the frontend login page.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "oauth2"
                ],
                "summary": "OAuth2 authorize",
                "parameters": [
                    {
                        "type": "string",
                        "description": "OAuth client ID",
                        "name": "client_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Registered redirect URI",
                        "name": "redirect_uri",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Must be code",
                        "name": "response_type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Space separated scopes",
                        "name": "scopes",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Opaque client state",
                        "name": "state",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "PKCE challenge",
                        "name": "code_challenge",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "PKCE method",
                        "name": "code_challenge_method",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "OIDC nonce",
                        "name": "nonce",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Redirect to frontend login or client redirect URI",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    }
                }
            }
        },
        "/api/v1/oauth2/token": {
            "post": {
                "description": "Exchanges an authorization code or refresh token for access, refresh, and ID tokens.",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "oauth2"
                ],
                "summary": "Exchange OAuth2 token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "authorization_code or refresh_token",
                        "name": "grant_type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authorization code",
                        "name": "code",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "PKCE verifier",
                        "name": "code_verifier",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "OAuth client ID",
                        "name": "client_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Redirect URI",
                        "name": "redirect_uri",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Refresh token",
                        "name": "refresh_token",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/oauth2dto.TokenResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    }
                }
            }
        },
        "/api/v1/users/me": {
            "get": {
                "description": "Returns the current authenticated user profile.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/usersdto.UserResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apperrors.HttpError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "apperrors.ErrorItem": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string"
                },
                "pointer": {
                    "type": "string"
                }
            }
        },
        "apperrors.HttpError": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/apperrors.ErrorItem"
                    }
                },
                "instance": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "authdto.ForgotPasswordDTO": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 255
                }
            }
        },
        "authdto.ForgotPasswordResponse": {
            "type": "object",
            "properties": {
                "submitted": {
                    "type": "boolean"
                }
            }
        },
        "authdto.LoginDTO": {
            "type": "object",
            "required": [
                "continue",
                "email",
                "password"
            ],
            "properties": {
                "continue": {
                    "type": "string",
                    "maxLength": 2000
                },
                "email": {
                    "type": "string",
                    "maxLength": 255
                },
                "password": {
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 8
                }
            }
        },
        "authdto.LogoutResponse": {
            "type": "object",
            "properties": {
                "loggedOut": {
                    "type": "boolean"
                }
            }
        },
        "authdto.RegisterDTO": {
            "type": "object",
            "required": [
                "continue",
                "email",
                "password"
            ],
            "properties": {
                "continue": {
                    "type": "string",
                    "maxLength": 2000
                },
                "displayName": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "email": {
                    "type": "string",
                    "maxLength": 255
                },
                "password": {
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 8
                }
            }
        },
        "authdto.ResetPasswordDTO": {
            "type": "object",
            "required": [
                "password",
                "token"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 8
                },
                "token": {
                    "type": "string",
                    "maxLength": 512
                }
            }
        },
        "authdto.ResetPasswordResponse": {
            "type": "object",
            "properties": {
                "reset": {
                    "type": "boolean"
                }
            }
        },
        "authdto.ResetPasswordValidationResponse": {
            "type": "object",
            "properties": {
                "reason": {
                    "type": "string"
                },
                "valid": {
                    "type": "boolean"
                }
            }
        },
        "authdto.SessionResponse": {
            "type": "object",
            "properties": {
                "authenticated": {
                    "type": "boolean"
                },
                "user": {
                    "$ref": "#/definitions/authdto.SessionUserResponse"
                }
            }
        },
        "authdto.SessionUserResponse": {
            "type": "object",
            "properties": {
                "avatarUrl": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "gamificationdto.AchievementResponse": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "level": {
                    "type": "integer"
                },
                "unlockedAt": {
                    "type": "string"
                }
            }
        },
        "gamificationdto.MeResponse": {
            "type": "object",
            "properties": {
                "achievements": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/gamificationdto.AchievementResponse"
                    }
                },
                "stats": {
                    "$ref": "#/definitions/gamificationdto.StatsResponse"
                }
            }
        },
        "gamificationdto.StatsResponse": {
            "type": "object",
            "properties": {
                "level": {
                    "type": "integer"
                },
                "nextLevelXp": {
                    "type": "integer"
                },
                "sessionsAdmined": {
                    "type": "integer"
                },
                "sessionsParticipated": {
                    "type": "integer"
                },
                "tasksEstimated": {
                    "type": "integer"
                },
                "xp": {
                    "type": "integer"
                }
            }
        },
        "health.LivenessStatus": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                },
                "uptime": {
                    "type": "string"
                }
            }
        },
        "health.ReadinessStatus": {
            "type": "object",
            "properties": {
                "db": {
                    "type": "string"
                },
                "redis": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "uptime": {
                    "type": "string"
                }
            }
        },
        "historydto.RoomSummaryOverview": {
            "type": "object",
            "properties": {
                "adminUser": {
                    "$ref": "#/definitions/historydto.RoomSummaryUserRef"
                },
                "approxDurationSeconds": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "estimatedTasksCount": {
                    "type": "integer"
                },
                "finishedAt": {
                    "type": "string"
                },
                "lastActivityAt": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "participantsCount": {
                    "type": "integer"
                },
                "roomId": {
                    "type": "string"
                },
                "roundCount": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "tasksCount": {
                    "type": "integer"
                },
                "teamId": {
                    "type": "string"
                }
            }
        },
        "historydto.RoomSummaryParticipant": {
            "type": "object",
            "properties": {
                "avatarUrl": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "estimatedTasksVotedCount": {
                    "type": "integer"
                },
                "guestName": {
                    "type": "string"
                },
                "joinedAt": {
                    "type": "string"
                },
                "leftAt": {
                    "type": "string"
                },
                "participantId": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                },
                "votesCastCount": {
                    "type": "integer"
                }
            }
        },
        "historydto.RoomSummaryResponse": {
            "type": "object",
            "properties": {
                "overview": {
                    "$ref": "#/definitions/historydto.RoomSummaryOverview"
                },
                "participants": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/historydto.RoomSummaryParticipant"
                    }
                },
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/historydto.RoomSummaryTask"
                    }
                }
            }
        },
        "historydto.RoomSummaryTask": {
            "type": "object",
            "properties": {
                "approxDurationSeconds": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "externalKey": {
                    "type": "string"
                },
                "finalEstimateValue": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "roundCount": {
                    "type": "integer"
                },
                "rounds": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/historydto.RoomSummaryTaskRound"
                    }
                },
                "status": {
                    "type": "string"
                },
                "taskId": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "historydto.RoomSummaryTaskRound": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "eligibleParticipantIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "roundNumber": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "votes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/historydto.RoomSummaryVote"
                    }
                }
            }
        },
        "historydto.RoomSummaryUserRef": {
            "type": "object",
            "properties": {
                "avatarUrl": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "historydto.RoomSummaryVote": {
            "type": "object",
            "properties": {
                "avatarUrl": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "guestName": {
                    "type": "string"
                },
                "participantId": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "historydto.SessionListItem": {
            "type": "object",
            "properties": {
                "approxDurationSeconds": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "estimatedTasksCount": {
                    "type": "integer"
                },
                "finishedAt": {
                    "type": "string"
                },
                "lastActivityAt": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "participantsCount": {
                    "type": "integer"
                },
                "role": {
                    "type": "string"
                },
                "roomId": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "tasksCount": {
                    "type": "integer"
                },
                "teamId": {
                    "type": "string"
                }
            }
        },
        "historydto.SessionListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/historydto.SessionListItem"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "oauth2dto.TokenResponseDTO": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "description": "in seconds",
                    "type": "integer"
                },
                "id_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "token_type": {
                    "description": "\"Bearer\"",
                    "type": "string"
                }
            }
        },
        "usersdto.UserResponse": {
            "type": "object",
            "properties": {
                "avatarUrl": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "githubId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lastLoginAt": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Estimate Room API",
	Description:      "WebSocket-based room estimation service.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
