apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-api-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notes-api
  template:
    metadata:
      labels:
        app: notes-api
    spec:
      containers:
      - name: notes-api-container
        image: masterbogdan0/ephermal-notes:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 8000
        envFrom:
          - configMapRef:
              name: notes-api-config
          - secretRef:
              name: note-api-secret
        readinessProbe:
          httpGet:
            path: /api/v1/health/readyz
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /api/v1/health/healthz
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 2
