fullnameOverride: metrics-server

apiService:
  create: true
  insecureSkipTLSVerify: false

tls:
  type: cert-manager
  certManager:
    existingIssuer:
      enabled: true
      kind: ClusterIssuer
      name: homelab-ca

resources:
  requests:
    cpu: 100m
    memory: 200Mi
