apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: headlamp-auth-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-dev
  target:
    name: headlamp-auth-dev
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: kv/dev/headlamp
        property: oidc_client_id
    - secretKey: client_secret
      remoteRef:
        key: kv/dev/headlamp
        property: oidc_client_secret
