fullnameOverride: headlamp

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

config:
  oidc:
    secret:
      create: false

clusterRoleBinding:
  create: false

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
