apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: headlamp-auth-staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-staging
  target:
    name: headlamp-auth-staging
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: kv/staging/headlamp
        property: oidc_client_id
    - secretKey: client_secret
      remoteRef:
        key: kv/staging/headlamp
        property: oidc_client_secret
