apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging-observability
resources:
  - ../../base
  - clusterrolebinding.yaml

patches:
  - target:
      kind: HTTPRoute
      name: http-headlamp
    path: httproute-patch.yaml

helmCharts:
  - name: headlamp
    repo: https://kubernetes-sigs.github.io/headlamp/
    version: "0.38.0"
    releaseName: headlamp
    namespace: staging-observability
    includeCRDs: false
    valuesFile: values-staging.yaml
