apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-prod
  target:
    name: n8n-prod
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        postgres-password: "{{ .postgres_password }}"
        redis-password: "{{ .redis_password }}"
        N8N_ENCRYPTION_KEY: "{{ .encryption_key }}"
        DB_TYPE: "postgresdb"
        DB_POSTGRESDB_HOST: "{{ .postgres_host }}"
        DB_POSTGRESDB_PORT: "{{ .postgres_port }}"
        DB_POSTGRESDB_DATABASE: "{{ .postgres_database }}"
        DB_POSTGRESDB_USER: "{{ .postgres_user }}"
        DB_POSTGRESDB_PASSWORD: "{{ .postgres_password }}"
        QUEUE_BULL_REDIS_HOST: "{{ .redis_host }}"
        QUEUE_BULL_REDIS_PORT: "{{ .redis_port }}"
        QUEUE_BULL_REDIS_USERNAME: "{{ .redis_username }}"
        QUEUE_BULL_REDIS_PASSWORD: "{{ .redis_password }}"
  data:
    - secretKey: postgres_host
      remoteRef:
        key: kv/prod/n8n
        property: postgres_host
    - secretKey: postgres_port
      remoteRef:
        key: kv/prod/n8n
        property: postgres_port
    - secretKey: postgres_database
      remoteRef:
        key: kv/prod/n8n
        property: postgres_database
    - secretKey: postgres_user
      remoteRef:
        key: kv/prod/n8n
        property: postgres_user
    - secretKey: postgres_password
      remoteRef:
        key: kv/prod/n8n
        property: postgres_password
    - secretKey: redis_host
      remoteRef:
        key: kv/prod/n8n
        property: redis_host
    - secretKey: redis_port
      remoteRef:
        key: kv/prod/n8n
        property: redis_port
    - secretKey: redis_username
      remoteRef:
        key: kv/prod/n8n
        property: redis_username
    - secretKey: redis_password
      remoteRef:
        key: kv/prod/n8n
        property: redis_password
    - secretKey: encryption_key
      remoteRef:
        key: kv/prod/n8n
        property: encryption_key
